// <auto-generated />
namespace StationCAD.Model.IdentityDBMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Address_Apartment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Address_Apartment));
        
        string IMigrationMetadata.Id
        {
            get { return "201608121818072_Address_Apartment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
