// <auto-generated />
namespace StationCAD.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Table_IncidentDateTimeNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table_IncidentDateTimeNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201608041428516_Table_Incident-DateTime-Nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
